### ISSUE TITLE
Create a limit for maximum cached entities

### ISSUE THREAD

**Issue by bennyn** [wireapp/wire-webapp-cryptobox#19]
- Introduce a limit
- Don't cache an unlimited amount of prekeys, sessions, etc.

**Comment by bennyn** [comment]
Create something like a LRU (Least Recently Used) Cache

**Comment by Yserz** [comment]
We are using [wire-webapp-lru-cache](https://github.com/wireapp/wire-webapp-lru-cache) now. Therefore the issue can be closed.
